import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import { Providers } from "./providers/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Providers>
          <Navbar navStyles="z-50" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
