import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/layout/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=" relative"
      >
        <Navbar className="z-50 fixed top-6 left-[50%] translate-x-[-50%] rounded-[22px]"/>
        {children}
      </body>
    </html>
  );
}
